#!/usr/bin/env bash

prefix="vcw_module_hkvb_bash_rest__$1"
prefix="vcw_module_hkvb_bash_rest__$1"

if [[ "vcw_module_hkvb_bash_rest__module_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_bash_rest__module_data_volume
fi

if [[ "vcw_module_hkvb_bash_rest__module_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_bash_rest__module_data_volume:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console untar /source/hkvb/bash/rest/_module/volumes/module_data_volume.tar
fi
