#!/usr/bin/env bash

prefix="vcw_module_hkvb_bash_api__$1"
prefix="vcw_module_hkvb_bash_api__$1"

if [[ "vcw_module_hkvb_bash_api__api_api_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_bash_api__api_api_volume
fi

if [[ "vcw_module_hkvb_bash_api__api_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_bash_api__api_data_volume
fi

if [[ "vcw_module_hkvb_bash_api__api_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_bash_api__api_data_volume:/vcw/pwd ${VCW_REGISTRY}hkvb/infometis console untar /source/hkvb/bash/api/_module/volumes/api_data_volume.tar
fi
