FROM ${VCW_REGISTRY}bash:5.0.18

RUN apk update && apk add curl && apk add coreutils && apk add gettext && apk add jq && rm -rf /var/cache/apk/*

LABEL co.vcweb.schema-version="1.0" \
      co.vcweb.label="hkvb/bash.base Image - External Build" \
      co.vcweb.description="Bash image with some additional library installs." \
      co.vcweb.realm="hkvb" \
      co.vcweb.image="bash.base" \
      co.vcweb.tag="5.0.18" \
      co.vcweb.maintainer="infomets@vcweb.co"
